config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :grades
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :attendances
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
  has_many :students
  has_many :lessons

    # def start_date
    #   start_date.strftime("%D, %M, %Y")
    # end

    # def end_date
    #   end_date.strftime("%D, %M, %Y")
    # end

    # def start_time
    #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    # end
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  #   def start_format
  #   start.strftime("%B %-d, %-l:%M %p")
  # end

  # def start_format_2
  #   start.strftime("%-l:%M %p")
  # end

  # def start_time
  #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  # end

end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  belongs_to :course
  has_many :lessons
  has_one :teacher, through: :course
  # has_many :courses
  # has_many :teachers, through: :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

has_many :courses
has_many :students, through: :courses

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:exam_category_id, :name, :start_date)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # skip_before_action :authenticate_student!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    # raise
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :password, :gender, :dob, :phone, :address, :image, :image_cache, :parent_id, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>
  <% DateTime.now.strftime("%d/%m/%Y - %H:%M %p") %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div align="center" class="image-uploader">
        <a href="#!">
          <%= image_tag f.object.image, size: '150x150' %>
          <%= f.input :image, as: :file, label: 'Upload Image' %>
          <%= f.hidden_field :image_cache %>
        </a>


      </div>
      <%= f.input :name %>
      <%= f.input :parent_id, collection: Parent.all %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :dob, as: :date, start_year: Date.today.year - 60,
                             end_year: Date.today.year - 12, discard_day: false,
                              order: [:day, :month, :year] %>
      <%= f.input :phone %>
      <%= f.input :gender, collection: Student::GENDER %>
      <%= f.input :address %>
      <%= f.input :course_id, collection: Course.all %>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= f.input :lat, as: :hidden, input_html: {id: 'teacher-lat'} %>
      <%= f.input :long, as: :hidden, input_html: {id: 'teacher-long'} %>
      <div id="map-teacher"></div>
    </div>
  </div>
  <%= f.button :submit, class: 'btn btn-primary btn-fill' %>
<% end %>

app/views/students/edit.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Edit Student</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to students_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to @student, class: 'btn btn-info btn-fill' do %>
        <i class="fa fa-eye"></i>
        Show
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/students/index.html.erb
<% if user_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Listing Students
      </h4>
      <hr/>
      <%= link_to new_student_path, class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-plus-square"></i>
        New Student
      <% end %>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td>
                <%= student.name %>
              </td>
              <td>
                <%= student.gender %>
              </td>
              <td>
                <%= student.phone %>
              </td>
              <td>
                <%= student.address %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
                <%= link_to edit_student_path(student), class: 'btn btn-primary btn-sm' do %>
                  <i class="fa fa-edit"></i>
                  Edit
                <% end %>
                <%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                  <i class="fa fa-trash"></i>
                  Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% teacher_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Your Students
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% current_teacher.students.each do |student| %>
            <tr>
              <td>
                <%= student.name %>
              </td>
              <td>
                <%= student.gender %>
              </td>
              <td>
                <%= student.phone %>
              </td>
              <td>
                <%= student.address %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% parent_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-users"></i>
        Seus filhos
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% current_parent.students.each do |student| %>
            <tr>
              <td>
                <%= student.name %>
              </td>
              <td>
                <%= student.gender %>
              </td>
              <td>
                <%= student.phone %>
              </td>
              <td>
                <%= student.address %>
              </td>
              <td>
                <%= link_to student, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% else %>
<% end %>

app/views/students/new.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">New Student</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to students_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/students/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Student</h4>
      <hr/>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <table class="table">
            <tr>
              <th>Image</th>
              <td>
                <%= image_tag @student.image, size: '150x150' %>
              </td>
            </tr>
            <tr>
              <th>Name</th>
              <td>
                <%= @student.name %>
              </td>
            </tr>
            <tr>
              <th>Parent Name</th>
              <td>
                <%= link_to "#{@student.parent.name}", @student.parent %>
              </td>
            </tr>
            <tr>
              <th>Gender</th>
              <td>
                <%= @student.gender %>
              </td>
            </tr>
            <tr>
              <th>Date of Birth</th>
              <td>
                <%= @student.dob %>
              </td>
            </tr>
            <tr>
              <th>Phone</th>
              <td>
                <%= @student.phone %>
              </td>
            </tr>
            <tr>
              <th>Email</th>
              <td>
                <%= @student.email %>
              </td>
            </tr>
            <tr>
              <th>Address</th>
              <td>
                <%= @student.address %>
              </td>
            </tr>
            <tr>
              <th>Course</th>
              <% if @student.course != nil %>
              <td>
                <%= link_to "#{@student.course.name}", @student.course %>
              </td>
              <% else %>
              <td>
                You're not enrolled in any course yet
              </td>
              <% end %>
            </tr>
             <tr>
              <% if @student.course != nil %>
              <th>Teacher</th>
              <td>
                <%= @student.teacher.name %>
              </td>
              <% else %>
              <td>
                <p></p>
              </td>
              <% end %>
            </tr>
          </table>
        </div>
        <div class="col-md-6 col-xs-12">
          <input id="lat-value" type="hidden" value="<%= @student.lat %>"></input>
          <input id="long-value" type="hidden" value="<%= @student.long %>"></input>
          <div id="show-student-map"></div>
        </div>
      </div>
    </div>
    <div class="footer">
      <%= link_to students_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
      <%= link_to edit_student_path(@student), class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-edit"></i>
        Edit
      <% end %>
    </div>
    <br/>
  </div>
</div>