config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :grades
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :attendances
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
  has_many :students
  has_many :lessons

    # def start_date
    #   start_date.strftime("%D, %M, %Y")
    # end

    # def end_date
    #   end_date.strftime("%D, %M, %Y")
    # end

    # def start_time
    #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    # end
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  #   def start_format
  #   start.strftime("%B %-d, %-l:%M %p")
  # end

  # def start_format_2
  #   start.strftime("%-l:%M %p")
  # end

  # def start_time
  #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  # end

end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  belongs_to :course
  has_many :lessons
  has_one :teacher, through: :course
  # has_many :courses
  # has_many :teachers, through: :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

has_many :courses
has_many :students, through: :courses

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:exam_category_id, :name, :start_date)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    if current_user
     @lessons = Lesson.all
    elsif current_teacher
     if current_teacher.courses != nil
     lessons_array = []
     @teacher_courses = current_teacher.courses.map { |course| lessons_array << course.lessons }
     @lessons = lessons_array
    elsif current_student
      @lessons = current_student.course.lessons
     end
    end
  end

  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:course_id, :name, :material)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.date_field :start_date %>
  <%= f.date_field :end_date %>
  <%= f.input :name %>
  <%= f.input :material %>
  <%= f.input :course_id, collection: Course.all %>
  <%= f.submit "Create lesson", class: "btn btn-talk" %>
<% end %>


<!-- check view/lessons/new for form for dates time -->

app/views/lessons/create.html.erb
<%= simple_form_for([ user, lesson ], remote: true) do |f| %>
  <%= f.input :start, input_html: {placeholder: "#{DateTime.now}"} %>
  <%= f.input :price, input_html: {placeholder: "$"} %>
  <%= f.input :name %>
  <%= f.input :material %>
  <%= f.submit "Add this lesson to your profile", class: "btn btn-talk" %>
<% end %>

app/views/lessons/create.js.erb
function refreshForm2(innerHTML) {
  const newLessonForm = document.querySelector('#new_lesson');
  newLessonForm.innerHTML = innerHTML;
}

function addLesson(LessonHTML) {
  const lessons = document.querySelector('#lessons');
  lessons.innerHTML = lessons.innerHTML + lessonHTML;
}

<% if @lesson.errors.any? %>
  refreshForm2('<%= j render "lessons/form", user: @user, lesson: @lesson %>');
<% else %>
  addLesson('<%= j render "lessons/show", lesson: @lesson %>');
  refreshForm2('<%= j render "lessons/form", user: @user, lesson: Lesson.new %>');
<% end %>

app/views/lessons/edit.html.erb
<h1>Lessons#edit</h1>
<p>Find me in app/views/lessons/edit.html.erb</p>

app/views/lessons/index.html.erb
<% if user_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Listing Lessons
      </h4>
      <hr/>
      <%= link_to new_lesson_path, class: 'btn btn-primary btn-fill' do %>
        <i class="fa fa-plus-square"></i>
        New Lesson
      <% end %>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Course name</th>
            <th>Name</th>
            <th>Material</th>
            <th>Teacher name</th>
          </tr>
        </thead>
        <tbody>
          <% @lessons.each do |lesson| %>
            <tr>
               <td>
                <%= lesson.course.name %>
              </td>
              <td>
                <%= lesson.name %>
              </td>
              <td>
                <%= lesson.material %>
              </td>
               <td>
                <%= lesson.course.teacher.name %>
              </td>
              <td>
                <%= link_to lesson, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
                <%= link_to edit_lesson_path(lesson), class: 'btn btn-primary btn-sm' do %>
                  <i class="fa fa-edit"></i>
                  Edit
                <% end %>
                <%= link_to lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
                  <i class="fa fa-trash"></i>
                  Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% teacher_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Listing your lessons
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Course</th>
            <th>Date</th>
            <th>Name</th>
            <th>Material</th>
          </tr>
        </thead>
        <tbody>
          <% @lessons.each do |lesson| %>
          <% lesson.each do |child| %>
            <tr>
              <td>
                <%= child.course.name %>
              </td>
              <td>
                <%= child.start_date %>
              </td>
              <td>
                <%= child.name %>
              </td>
              <td>
                <%= child.material %>
              </td>
              <td>
                <%= link_to child, class: 'btn btn-info btn-sm' do %>
                  <i class="fa fa-eye"></i>
                  Show
                <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% student_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
     <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Suas Aulas
      </h4>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Materiais</th>
            <th>Dia</th>
            <th>dia</th>
            <th>Ir para Aula</th>
          </tr>
        </thead>
            <% current_student.course.lessons.each do |lesson| %>
        <tbody>
            <tr>
              <td>
                <%= lesson.name %>
              </td>
              <td>
                <%= lesson.material %>
              </td>
              <td>
                <%= lesson.start_date %>
              </td>
               <td>
                <%= lesson.end_date %>
              </td>
              <td>
                <%= link_to 'AULA', lesson %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <br/>
  </div>
</div>
<% elsif %>
<% parent_signed_in? %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">
        <i class="pe-7s-ribbon"></i>
        Aulas
      </h4>
      <hr/>
      <br/>
      <br/>
    </div>
    <div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
      </table>
    </div>
    <br/>
  </div>
</div>
<% else %>
<p>Private page</p>
<% end %>

app/views/lessons/new.html.erb
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">New Lesson</h4>
      <hr/>
    </div>
    <div class="content">
      <%= render 'form' %>
    </div>
    <hr/>
    <div class="footer">
      <%= link_to courses_path, class: 'btn btn-default' do %>
        <i class="fa fa-chevron-left"></i>
        Back
      <% end %>
    </div>
    <br/>
  </div>
</div>

app/views/lessons/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="col-xs-12 col md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Lessons</h4>
      <hr/>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <table class="table">
              <th>Name</th>
              <td>
                <%= @lesson.name %>
              </td>
            </tr>
              <th>Material</th>
              <td>
                <%= @lesson.material %>
              </td>
            </tr>
          </table>
        </div>
    </div>
    <br/>
  </div>
</div>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>