config/routes.rb
Rails.application.routes.draw do

  scope 'auth' do
    devise_for :parents
    devise_for :teachers
    devise_for :students
    devise_for :users
  end

  resources :users
  resources :parents
  resources :teachers
  # resources :exam_categories
  resources :grades
  resources :lessons

  resources :students
  # resources :exams
  resources :courses
  resources :attendances
  resources :lessons

  # root 'dashboard#index'
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :grade
  belongs_to :teacher
  has_many :students
  has_many :lessons

    # def start_date
    #   start_date.strftime("%D, %M, %Y")
    # end

    # def end_date
    #   end_date.strftime("%D, %M, %Y")
    # end

    # def start_time
    #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    # end
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_many :courses
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course

  #   def start_format
  #   start.strftime("%B %-d, %-l:%M %p")
  # end

  # def start_format_2
  #   start.strftime("%-l:%M %p")
  # end

  # def start_time
  #   self.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  # end

end

app/models/parent.rb
class Parent < ApplicationRecord

  has_many :students

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

  GENDER = ['Male', 'Female']

end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :parent
  belongs_to :course
  has_many :lessons
  has_one :teacher, through: :course
  # has_many :courses
  # has_many :teachers, through: :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, StudentUploader

GENDER = ['Male', 'Female']
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

has_many :courses
has_many :students, through: :courses

  mount_uploader :image, TeacherUploader

  GENDER = ['Male', 'Female']

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="School Management" name="description"/>
    <meta content="School Management" name="Nhean"/>
    <title>EnglishBee</title>
    <script defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkSX4YNQLqzBJPKdQKuESstJxUGFK7Jg8"></script>
    <%= csrf_meta_tags %>
    <%= javascript_tag "$('.selectpicker').selectpicker();" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="<%= controller_name %>_<%= params[:action] %>">
    <div class="wrapper">
    <% if user_signed_in? %>
      <%= render 'partials/sidebar' %>
      <% elsif %>
      <% parent_signed_in? %>
      <%= render 'partials/parents-sidebar' %>
      <% elsif %>
      <% student_signed_in? %>
      <%= render 'partials/students-sidebar' %>
      <% elsif %>
      <% teacher_signed_in? %>
      <%= render 'partials/teachers-sidebar' %>
      <% else %>
      <% end %>
      <div class="main-panel">
        <%= render 'partials/topnav' %>
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="School Management" name="description"/>
    <meta content="School Management" name="Nhean"/>
    <title>EnglishBee</title>
    <script defer="defer" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkSX4YNQLqzBJPKdQKuESstJxUGFK7Jg8"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="<%= controller_name %>_<%= params[:action] %>">
    <br/>
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <div class="card">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/partials/_parents-sidebar.html.erb
<% if parent_signed_in? %>
<div class="sidebar" data-color="yellow" data-image="/img/sidebar-4.jpg">

  <div class="sidebar-wrapper">
    <div class="logo">
      <a class="simple-text" href="#">
       PAIS
      </a>
    </div>
    <ul class="nav">
      <li>
        <a href="#">
          <i class="pe-7s-browser"></i>
          <p>CALENDARIO</p>
        </a>
      </li>
      <li>
        <%= link_to current_parent do %>
          <i class="pe-7s-id"></i>
          <p>PERFIL</p>
        <% end %>
        <li>
        <%= link_to students_url do %>
          <i class="pe-7s-study"></i>
          <p>Your Students</p>
        <% end %>
      </li>
      </li>
       <li>
        <%= link_to teachers_url do %>
          <i class="pe-7s-id"></i>
          <p>Professor</p>
        <% end %>
      </li>
      <li>
        <%= link_to courses_url do %>
          <i class="pe-7s-ribbon"></i>
          <p>Curso</p>
        <% end %>
      </li>
      <li>
        <%= link_to lessons_url do %>
          <i class="pe-7s-culture"></i>
          <p>Aulas</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/partials/_sidebar.html.erb
<% if user_signed_in? %>
<div class="sidebar" data-color="yellow" data-image="/img/sidebar-3.jpg">


  <div class="sidebar-wrapper">
    <div class="logo">
      <a class="simple-text" href="#">
        EnglishBee
      </a>
    </div>
    <ul class="nav">
      <li>
        <a href="#">
          <i class="pe-7s-graph"></i>
          <p>Dashboard</p>
        </a>
      </li>
      <li>
        <%= link_to users_path do %>
          <i class="pe-7s-user"></i>
          <p>User Profile</p>
        <% end %>
      </li>
      <li>
        <%= link_to students_url do %>
          <i class="pe-7s-study"></i>
          <p>Students</p>
        <% end %>
      </li>
      <li>
        <%= link_to teachers_url do %>
          <i class="pe-7s-id"></i>
          <p>Teachers</p>
        <% end %>
      </li>
      <li>
        <%= link_to parents_url do %>
          <i class="pe-7s-users"></i>
          <p>Parents</p>
        <% end %>
      </li>
      <li>
        <%= link_to courses_url do %>
          <i class="pe-7s-ribbon"></i>
          <p>Courses</p>
        <% end %>
      </li>
      <li>
        <%= link_to lessons_url do %>
          <i class="pe-7s-culture"></i>
          <p>Lessons</p>
        <% end %>
      </li>
      <li>
        <%= link_to grades_url do %>
          <i class="pe-7s-note2"></i>
          <p>Grade</p>
        <% end %>
      </li>
      <li>
        <%= link_to attendances_url do %>
          <i class="pe-7s-note2"></i>
          <p>Attendance</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>
  <% end %>

app/views/partials/_students-sidebar.html.erb
<% if student_signed_in? %>
<div class="sidebar" data-color="yellow" data-image="/img/sidebar-4.jpg">

  <div class="sidebar-wrapper">
    <div class="logo">
      <a class="simple-text" href="#">
       ALUNO
      </a>
    </div>
    <ul class="nav">
      <li>
        <a href="#">
          <i class="pe-7s-browser"></i>
          <p>SEU CALENDARIO</p>
        </a>
      </li>
      <li>
        <%= link_to current_student do %>
          <i class="pe-7s-id"></i>
          <p>PERFIL</p>
        <% end %>
      </li>
       <li>
        <%= link_to teachers_url do %>
          <i class="pe-7s-id"></i>
          <p>Professor</p>
        <% end %>
      </li>
      <li>
        <%= link_to courses_url do %>
          <i class="pe-7s-ribbon"></i>
          <p>Curso</p>
        <% end %>
      </li>
      <li>
        <%= link_to lessons_url do %>
          <i class="pe-7s-culture"></i>
          <p>Aulas</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/partials/_teachers-sidebar.html.erb
<% if teacher_signed_in? %>
<div class="sidebar" data-color="yellow" data-image="/img/sidebar-4.jpg">
 <div class="sidebar-wrapper">
    <div class="logo">
      <a class="simple-text" href="#">
       TEACHERS
      </a>
    </div>
    <ul class="nav">
      <li>
        <a href="#">
          <i class="pe-7s-browser"></i>
          <p>Your Calendar</p>
        </a>
      </li>
      <li>
        <%= link_to current_teacher do %>
          <i class="pe-7s-id"></i>
          <p>Teacher Profile</p>
        <% end %>
      </li>
      <li>
        <%= link_to students_url do %>
          <i class="pe-7s-study"></i>
          <p>Your Students</p>
        <% end %>
      </li>
      <li>
        <%= link_to courses_url do %>
          <i class="pe-7s-ribbon"></i>
          <p>Courses</p>
        <% end %>
      </li>
      <li>
        <%= link_to lessons_url do %>
          <i class="pe-7s-culture"></i>
          <p>Lessons</p>
        <% end %>
      </li>
      <li>
        <%= link_to attendances_url do %>
          <i class="pe-7s-note2"></i>
          <p>Attendance</p>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% end %>

app/views/partials/_topnav.html.erb
<nav class="navbar navbar-default navbar-fixed">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target="#navigation-example-2" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <% if user_signed_in? %>
        Hello, <%=current_user.name %>
        <% elsif %>
          <% teacher_signed_in? %>
        Hello, <%=current_teacher.name %>
        <% elsif %>
          <% parent_signed_in? %>
        Hello, <%=current_parent.name %>
        <% elsif %>
          <% student_signed_in? %>
        Hello, <%=current_student.name %>
        <% end %>
      </a>
    </div>
    <div class="collapse navbar-collapse">
     <% if student_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user-circle-o"></i>
            My Account
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
           <li>
            <%= link_to current_student do %>
              <p>Profile</p>
            <% end %>
          </li>
            <li>
              <a href="#">
                <i class="fa fa-gears"></i>
                Setting
              </a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to destroy_student_session_url, method: :delete do %>
            <i class="fa fa-power-off"></i>
            Log out
          <% end %>
      </li>
      </ul>
      <% elsif %>
      <% user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user-circle-o"></i>
            My Account
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to current_user do %>
              <p>Profile</p>
            <% end %>
          </li>
              <a href="#">
                <i class="fa fa-gears"></i>
                Setting
              </a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to destroy_user_session_url, method: :delete do %>
            <i class="fa fa-power-off"></i>
            Log out
          <% end %>
      </li>
      </ul>
       <% elsif %>
      <% parent_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user-circle-o"></i>
            My Account
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
            <%= link_to current_parent do %>
              <p>Profile</p>
            <% end %>
          </li>
              <a href="#">
                <i class="fa fa-gears"></i>
                Setting
              </a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to destroy_parent_session_url, method: :delete do %>
            <i class="fa fa-power-off"></i>
            Log out
          <% end %>
      </li>
      </ul>
       <% elsif %>
      <% teacher_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user-circle-o"></i>
            My Account
            <b class="caret"></b>
          </a>
              <ul class="dropdown-menu">
           <li>
            <%= link_to current_teacher do %>
              <p>Profile</p>
            <% end %>
          </li>
            <li>
              <a href="#">
                <i class="fa fa-gears"></i>
                Setting
              </a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to destroy_student_session_url, method: :delete do %>
            <i class="fa fa-power-off"></i>
            Log out
          <% end %>
      </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
           <li>
                <i class="fas fa-sign-in-alt"></i>
                  Sign In
                   <b class="caret"></b>
                    <ul class="dropdown-menu">
              <li>
                 <%= link_to new_teacher_session_path do %>
                  <i class="pe-7s-id"></i>
                  Teacher
                <% end %>
              </li>
              <li>
                <%= link_to new_student_session_path do %>
                  <i class="pe-7s-study"></i>
                  Student
                <% end %>
              </li>
               <li>
                <%= link_to new_parent_session_path do %>
                   <i class="pe-7s-users"></i>
                  Parent
                <% end %>
              </li>
            </ul>
          </li>
           </a>
          </li>
        </ul>
    </div>
    <% end %>
  </nav>